language: android
jdk: oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - lynx
android:
  components:
  - platform-tools
  - tools
  - build-tools-27.0.2
  - android-27
  - extra-android-m2repository
before_install: chmod +x gradle/buildWithTravis.sh
script: gradle/buildWithTravis.sh
env:
  global:
  - secure: YFo+HowkRNFOLsJJY0PN7M9LqKoxdlt087jsAVm2vwXajqoXYL/r1lLZCry2bUw0hTi+AYKr1etuLgAc+NHb7Zi2LaTWh47nzqWwGLb1IYCBT7xFqVjLkbMdtf5v0OiNE4Psm68opQ9AkxOASAos7Hv+sg0AZCVLtw8WIsUPsHraq2A7YtFUKHmk0g2afEVZ4GJMHYQaPjYIyNLqFhkG6judt+4x64my8iEBvCyBqYPL1iKeNLeHqpt6S03eGa7dtWyudo+UFPKTZdVOhFbFbeaOKvp3UbvoaC6dqVSro6X1LbbCV/h8JNHIcDNd02eVBdhOPJrKwIvMJ63O6KlNkz7aVe1u7CHNKdSBFY7iP7ytvEpdWFO/lNqU2o02CUmRLfT5RTpNHvfLZ75HHBmbrd4EwIC8S8KcOVAdLevIQKyh9Im5TaeTpdbqvucbaeZocE3//9RaVNlxPPfPh5PZVc37buYtbWjVWvVT7A/1JBMcMWsmzW8Z9jLkEBkipnhWn7YbQTewPckwFiGuuDOBKZ24SU2xd0lFt1pRt4W0p5wosvpCudK60zn3CSEwKP4mSEX6pt6XS6dLI+/O53WH8XpBbcbHmlRytTRclUdsyU/OE5EzF9G39egSBkqszzazbkm9xyz93o+0hT1EdKld2b+E3lwa8QSpSG0JhoSoRWs=
  - secure: NxI9RMqeKmfeB7ZeLtNaXmfdDRQb9NRS5yvkdUszOx4HaJ7jZqMPCcDj8ks55eIkuVUU3vRy1r6Hx6U+OAlsqjjJlglui56jb6ZmL6QNb7+rQSq0WPyVh4cyEIxusEzFsuFXolqN+AFXbqk6k0Pwkg1WWFLiAeBitBo9W7bo6zztbWZMMucMFE0p/CC7ee1PHaq++xBUWlZBwgCcOmxc8ygIk11tnW8G5yKPD4BoyrX6Bze8KPAyY4XYrPclErIyZS0FljUFo8UPaEnTzu29BYhtTIcXpIoLmMG5TxBrlVm2//NiIrjNVQItQPklnTYPgBlR3uQVRMC4tMuIw6MESSfurUwRImIlGWSIHk1RiG/w/5FmcLLql/wGuC2wIEZuhQo45n0WzVZKf3Ri2aw7jsD0wF0nl+Bo6B5ZvJfWz6d8hYBX9lKs2lPh4SNXJCrv1MbSkgjgPl5AsVaSzxJhLHOeYqy8JHs/7C1y5ImRjgxEfu38hvHeTPAZdgGUd6fNoiNIllOLp4tjHDEBbLujtjbK53KagEraeiU17XhCitVwZTwPX+1tVVWEgGx4GTnifELUNvLqponMCgQG6fkPLufF9BzJbyAC1348YlBtgg30X+pHCBZS/s0NI73V0VLlDw/YkOg8EyLFWhNcc4JxlI/yNWthPCDE2X0hKgSpUUc=
